# Generated by Django 5.0.2 on 2026-01-10 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandate',
            name='is_near_expiry_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mandate',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mandate',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='mandates.mandate'),
        ),
        migrations.AlterField(
            model_name='mandate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Signature'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated Early'), ('TERMINATED_BY_USER', 'Terminated by User')], default='PENDING', max_length=20),
        ),
    ]
